# Generated by Django 3.2.9 on 2021-11-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211103_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='porfolio/images/courses')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shorName', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('nacionalty', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('github', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skils',
            field=models.ManyToManyField(blank=True, null=True, to='core.Skill'),
        ),
    ]
