# Generated by Django 3.2.9 on 2021-11-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211105_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
