# Generated by Django 3.2.9 on 2021-11-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maincontent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='cv',
            field=models.FileField(blank=True, default=None, max_length=150, null=True, upload_to='cv/'),
        ),
    ]
