# Generated by Django 3.2.9 on 2021-11-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_educations_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='educations',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='educations',
            name='level',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
