# Generated by Django 3.2.9 on 2021-11-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211105_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
