# Generated by Django 3.2.9 on 2021-11-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_maincontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='destacted',
            field=models.BooleanField(default=False),
        ),
    ]
