# Generated by Django 3.2.9 on 2023-07-17 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('start_at', models.DateField(default=django.utils.timezone.now)),
                ('end_at', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
